### PR TITLE
Explain why camelCase convention is recommended

### PR DESCRIPTION
**Pull request by josephrexme**

### CODE REVIEW

**Comment by joshwnj** [comment]
Looks good, thanks @bl4ckdu5t ! I only suggest one change of wording:

> You may encounter errors then resolve to using a bracket notation (style['class-name']) but a camelCase prevents this from occuring.

You can still work around kebab-case with bracket notation (eg. `style['class-name']`) but `style.className` is cleaner.

**Comment by bl4ckdu5t** [comment]
Thanks @joshwnj . I just made a fix with the suggested wording.

**Comment by taion** [comment]
I don't quite agree with this, BTW. Our style guide calls for using kebab-case in our CSS modules, then just enabling `camelCase` in `css-loader`, and using camelCase in our JS. Probably best to either use camelCase in CSS files, or enable the `camelCase` loader option, though.

**Comment by joshwnj** [comment]
@taion is there any rationale behind preferring kebab-case in your style guide?

**Comment by bl4ckdu5t** [comment]
I understand reasons why a style guide would prefer kebab-case. Before CSS modules I've always used kebab-case for CSS, camelCase for JS. This is not enforcing camel case in anyway. Just giving one reason why it is a recommended convention.

**Comment by taion** [comment]
Just a matter of taste – camel case in CSS looks weird.

@bl4ckdu5t What ESLint errors?

**Comment by sullenor** [comment]
Presumably from [eslint-plugin-css-modules](https://github.com/atfzl/eslint-plugin-css-modules).

**Comment by bl4ckdu5t** [comment]
Yes @sullenor that's what I mean @taion . I decided to just take that out. I was making an assumption that other people may be using that and experiencing errors. Sincerely, I agree camelCase classes are weird and I just tried to adapt to them but I think anyone using the `camelCase` option without that eslint plugin should be fine. Perhaps reconstructing the explanation and including the option of using that `css-loader` option would be better?

**Comment by joshwnj** [comment]
Everything looks weird when you're used to something else :)

But keep in mind, this is purely a recommendation - there's nothing wrong with choosing to use kebab-case. I think this PR is worth merging because it explains the reason behind the recommendation a little more.

Nonetheless I think there's a very strong reason to prefer camelCase when using css modules: it makes a clear link between the classnames in your css file and the object properties in your js file, without needing to wrap the names in bracket notation.

Personally I would not recommend something that automatically converts names from kebab-case to camelCase.  It's additional cpu & mental hurdle for purely subjective reasons, and also opens up some weird edge-cases (eg. what happens if you have both `.some-name` and `.someName` in the css? Which one does your JS get?)

**Comment by taion** [comment]
Makes sense to me.

**Comment by taion** [comment]
Any update here? What's the procedure on merging these changes?

**Comment by TrySound** [comment]
@taion Just ping :)

**Pull request merged**
